apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri
data:
  mongodb-uri: mongodb://tasky:prayformongo@3.80.129.13:27017/?authSource=admin

# apiVersion: v1
# data:
#   mongodb-uri: mongodb://tasky:prayformongo@44.203.250.134:27017/?authSource=admin
# kind: Secret
# type: Opaque


# apiVersion: v1
# data:
#   mongodb-uri: bW9uZ29kYjovL3Rhc2t5OnByYXlmb3Jtb25nb0A0NC4yMDMuMjUwLjEzNDoyNzAxNy8/YXV0aFNvdXJjZT1hZG1pbg==
# kind: Secret
# metadata:
#   creationTimestamp: "2024-04-04T17:54:06Z"
#   name: mongodb-uri
#   namespace: default
#   resourceVersion: "301966"
#   uid: e3b65732-e4ed-41ca-962d-2645d9d00dce
# type: Opaque
# ~                                                                                